### PR TITLE
Support for ASP.Net Core RC2

### PR DESCRIPTION
**Pull request by mattdwen**
This is an update to PR #292 to bring it up to date with ASP.NET Core RC2.

Supported frameworks are now `net451` and `netstandard1.5`.
I've set the version to be `rc2` to match ASP.NET Core itself.

### CODE REVIEW

**Comment by sirkirby** [comment]
@mattdwen thanks for doing this, hopefully they will merge it soon! I'm anxious to use this lib in my own library. While it's pending, have you thought about moving this right to the RTM release?

**Comment by mattdwen** [comment]
@sirkirby I was going to bring my projects up to RTM next week, so I'll probably update this at the same time.

**Comment by CmdrKeen** [comment]
+1 on the great work here @mattdwen :-) We have time allocated in this sprint (which ends at the end of next week) to formalise the release for .NET core 1.0 also. Your help has & is super appreciated, thank you!

**Comment by j5alive** [comment]
@mattdwen If you want to update this to RTM then we would greatly appreciate it. We could look to get it merged in next week or the one after depending on if/when you're able to finish. Let me know if you're keen otherwise I'll schedule someone in the team to do it. Thanks.

**Comment by mattdwen** [comment]
@j5alive I couldn't guarantee I could get it done next week, so please go ahead and schedule someone :) If I don't see any activity on it, I'll might ping you later on if I've got the time.

**Comment by j5alive** [comment]
Hi @mattdwen I've been able to get this updated this week and am just making some final tweaks to bring the namespaces and class names in line with our other clients. We're going to change the current `Mindscape.Raygun4Net.AspNetCore.RaygunAspNetCoreClient` class to `Mindscape.Raygun4Net.RaygunClient` 
Do you see any issues with this?
I'll look to push my branch today and get the PR ready for review by the team. Hopefully have a nuget package available by the end of the week.

**Comment by mattdwen** [comment]
Awesome work @j5alive! Good call on the namespacing. If you get the branch updated today I'll be able to test it against my project tomorrow.

**Pull request merged**
