### PR TITLE
For discussion only.

### PR DESCRIPTION
**Pull request by joshrobb**
Rename SendInBackground -> SendAsync. Make sending use IO completion ports rather than a Threadpool thread.

### CODE REVIEW

**Comment by abatishchev** [comment]
Any update on this, huh?

**Comment by jamiepenney** [comment]
@abatishchev All of the .NET providers have Send and SendInBackground overloads and we use SendInBackground by default whenever we set up error handlers automatically.

What update were you looking for specifically?

**Comment by willnogueira** [comment]
Is this something that will be added ?
I agree that the handle (i.e Task) should be returned to the caller in the Async version.
This relates to issue https://github.com/MindscapeHQ/raygun4net/issues/319

**Comment by mduncan26** [comment]
Closing this PR for now. If you wish to see this PR addressed please create a new one or post within our forums (https://raygun.com/forums). Thank you.

**Pull request closed without merging**
